spring:
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        hbm2ddl:
          import_files: import.sql
          auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # todo change
    url: jdbc:mysql://localhost:3306/china_cbc_management?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: root
    password: shuju
    hikari:
      prepStmtCacheSize: 256
      prepStmtCacheSqlLimit: 2048
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://10.234.51.122:8080/oauth2/jwks  # todo change

  redis:
    database: 0
    # todo change
    host: 10.234.50.38
    password: mlchiepukf
    redisson:
      singleServerConfig: |
        idleConnectionTimeout: 10000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        subscriptionsPerConnection: 5
        clientName: null
        subscriptionConnectionMinimumIdleSize: 1
        subscriptionConnectionPoolSize: 50
        connectionMinimumIdleSize: 24
        connectionPoolSize: 64
        database: 0
        dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.MarshallingCodec> { }
        transportMode: "NIO"

logging:
  level:
    org:
      springframework:
        security: TRACE
