/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    `maven-publish`
}

group = "com.lh.template"
version = "1.0-SNAPSHOT"

java {
    withJavadocJar()
    withSourcesJar()
}

tasks.javadoc {
    options.encoding = "UTF-8"
    if (JavaVersion.current().isJava9Compatible) {
        (options as StandardJavadocDocletOptions).addBooleanOption("html5", true)
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            versionMapping {
                usage("java-api") {
                    fromResolutionOf("runtimeClasspath")
                }
                usage("java-runtime") {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        maven {
            isAllowInsecureProtocol=true
            // change URLs to point to your repos, e.g. http://my.org/repo
            val releasesRepoUrl = uri("http://192.168.0.109:8081/repository/maven-releases/")
            val snapshotsRepoUrl = uri("http://192.168.0.109:8081/repository/maven-snapshots/")
            url = uri(if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl)
            credentials{
                username = "admin" //todo_lh 替换 catalog
                password = "admin123"

            }
        }
    }
}